- name: parquet
  type: Folder
- name: examples
  type: Folder
- name: Bridge Raw Data View
  type: EntityViewSchema
  scopes: ['{bridge_raw_data}']
  includeEntityTypes: ['file']
  addDefaultViewColumns: true
  addAnnotationColumns: true

